name = "Hana's Cobblemon Pack"
author = "BaLLducked, jadelily18"
version = "1.7.1-1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "def79e0eb50ef1f6d34268ae118fa3984a0b8ef432001c0e415970fd7ce2ca4b"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1", "1.20.1"]
datapack-folder = "datapacks"
