name = "Hana's Cobblemon Pack"
author = "BaLLducked, jadelily18"
version = "1.6.28a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7e13762a7a8f30dd9bd0c2110b4b49360d5807d2e8d00fccc2a583c3ae24986"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1", "1.20.1"]
datapack-folder = "datapacks"
